# -*- coding: utf-8 -*-
"""
Created on Sat Jul  3 18:51:02 2021

@author: blah
"""

# helper function for going from file names back to their character 
# file names themselves are non consistent, we rely on the autogenerated 
# folder names 


def getCharFromPath(filePath):
    # first step is deleting everything after the last backslash
    numChars = len(filePath)
    index = numChars -1
    while True: 
        if filePath[index] == '\\': 
            break 
        index = index -1
    
    # now truncate 
    tempFile = filePath[:index]
    
    # now we do it again, but this time we drop the head
    index = len(tempFile) - 1
    while True: 
        if tempFile[index] == '\\': 
            break 
        index = index -1

    tempFile = tempFile[index+1:]
    
    # two more times, this time using the dashes 
    
    index = len(tempFile) -1
    while True: 
        if tempFile[index] == '-': 
            break 
        index = index -1
    tempFile = tempFile[:index]
    
    index = len(tempFile) -1
    while True: 
        if tempFile[index] == '-': 
            break 
        index = index -1
    tempFile = tempFile[index+1:]
    
    
    
    return tempFile